variables:
  #<domain>/<docker id>/<repo>:<tag + commit>
  #docker.io/hoanglee/shoeshop:v0.0.1_afsssesds
  dockerImage: ${registry_url}/hoanglee/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}

stages:
  - buildAndPush
  - deloy
  - showlog
# buildAndPush: # tên của job
#   stage: buildAndPush
#   # trước khi chạy lệnh docker build và docker push thì cần phải đăng nhập vào docker registry
#   before_script:
#     - docker login -u ${registry_user} -p ${registry_password} ${registry_url}
#   script:
#     - docker build -t ${dockerImage} -f DockerFile .
#     - docker push ${dockerImage}
#   tags:
#     - gitlab-servers # tag của runner
#   only:
#     - tags # chỉ chạy khi có tag
deloy: # tên của job
  stage: deloy
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u ${registry_user} -p ${registry_password} ${registry_url}
  script:
    - docker pull ${dockerImage}
    - docker rm -f ${CI_PROJECT_NAME}
    - docker run --name ${CI_PROJECT_NAME} -dp 8084:8080 ${dockerImage}
  tags:
    - gitlab-servers # tag của runner
  only:
    - tags # chỉ chạy khi có tag

showlog:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 20
    - docker logs ${CI_PROJECT_NAME}
  tags:
    - gitlab-servers # tag của runner
  only:
    - tags # chỉ chạy khi có tag
