variables:
  projectName: "shoe-ShopingCart"
  projectVersion: "0.0.1-SNAPSHOT"
  projectPort: "8081"
  projectUser: "shoeshop"
  projectPath: "/datas/${projectUser}"
  projectJar: "${projectName}-${projectVersion}.jar"

stages:
  - build
  - deloy
  - project
  - checking
build: # tên của job
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - mvn clean install
  tags:
    - gitlab-servers # tag của runner
  # only:
  #   - tags # chỉ chạy khi có tag
deloy: # tên của job
  stage: deloy
  variables:
    GIT_STRATEGY: none
  script:
    # chuyển file jar vào thư mục /datas/shoeshop
    - sudo cp target/${projectJar} ${projectPath}
    # chuyển quyền sở hữu thư mục /datas/shoeshop cho user shoeshop
    - sudo chown -R ${projectUser} ${projectPath}
    # -c có nghĩa là sau khi chạy su shoeshop thì sẽ chạy lệnh cd /datas/shoeshop && nohup java -jar shoe-ShoppingCart-0.0.1-SNAPSHOT.jar > app.log &
    - sudo su ${projectUser} -c "cd ${projectPath} && nohup java -jar ${projectJar} > nohup.out 2>&1  &"
  tags:
    - gitlab-servers # tag của runner
  # only:
  #   - tags # chỉ chạy khi có tag
