stages:
  - build
  - deloy
  - project
  - checking
build: # tên của job
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - mvn clean install
  tags:
    - gitlab-servers # tag của runner
deloy: # tên của job
  stage: deloy
  variables:
    GIT_STRATEGY: none
  script:
    # kill process java đang chạy
    - ps -ef | grep shoe-ShopingCart-0.0.1-SNAPSHOT.jar | grep -v grep | awk '{print $2}' | xargs kill -9
    # chuyển file jar vào thư mục /datas/shoeshop
    - sudo cp target/shoe-ShopingCart-0.0.1-SNAPSHOT.jar /datas/shoeshop
    # chuyển quyền sở hữu thư mục /datas/shoeshop cho user shoeshop
    - sudo chown -R shoeshop /datas/shoeshop
    # -c có nghĩa là sau khi chạy su shoeshop thì sẽ chạy lệnh cd /datas/shoeshop && nohup java -jar shoe-ShoppingCart-0.0.1-SNAPSHOT.jar > app.log &
    - sudo su shoeshop -c "cd /datas/shoeshop && nohup java -jar shoe-ShopingCart-0.0.1-SNAPSHOT.jar > app.log &"
  tags:
    - gitlab-servers # tag của runner
